### PR TITLE
Pass through @JacksonXmlProperty annotations

### LINKED ISSUE #294: FreeBuilder should respect @JacksonXmlProperty annotations
Jackson allows methods to be serialized to and de-serialized from different XML and JSON representations by using a combinations of the `@JsonProperty` and `@JacksonXmlProperty` annotations.
Currently, FreeBuilder [looks for only `@JsonProperty`](https://github.com/inferred/FreeBuilder/blob/master/src/main/java/org/inferred/freebuilder/processor/JacksonSupport.java#L40) and adds them to the result. 
This makes FreeBuilder unsuitable for situations where a class need to have different XML and JSON representations.

### PR DESCRIPTION
**Pull request by sdqali**
This fixes #294

### CODE REVIEW

**Comment by chrisalice** [comment]
Until I get a CLA hook set up, could you please sign this branch to indicate you accept https://developercertificate.org/ ? i.e. that the contribution is yours to submit and that you understand you are releasing it under the terms of the [Apache License 2.0] laid out in the LICENSE.txt file. If you agree, please run

```git commit --allow-empty --sign-off```

and push the commit.

[Apache License 2.0]: http://www.apache.org/licenses/LICENSE-2.0

**Comment by alicederyn** [comment]
Oh, and that you are happy for your copyright to be summarized as "inferred.org". I will consider this equivalent to signing any CLA I may set up in future with the same terms. Just want to make sure everything is totally understood and kosher :)

**Comment by sdqali** [comment]
Thanks for reviewing, @alicederyn 

- I have now signed the Google CLA.

**Comment by alicederyn** [comment]
Having some issues with the OSS release mechanism. Will let you know when I get this out the door.

**Comment by alicederyn** [comment]
Just to keep you posted, the Maven Central Gradle plugin appears to be permanently broken. I'm investigating releasing through BinTray on a personal project, if that works I'll get FreeBuilder into it too. So sorry for the delay!

**Comment by sdqali** [comment]
No worries. Thank you for the update.

**Comment by alicederyn** [comment]
I am currently just awaiting BinTray's approval to publish to JCenter (a once-per-project step involving a remote human that's a prerequisite for publishing to Maven Central).

**Pull request merged**
